name: Build and Release Libraries

on:
  workflow_dispatch:

env:
  BUILD_TYPE: Release
  PYTHONUTF8: 1

permissions:
  contents: write
  id-token: write

jobs:
  build_libraries:
    name: Build Libraries
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-22.04
            arch: amd64
            target: x86_64-linux-gnu
            name_suffix: linux_amd64
            extension: .so
          - os: ubuntu-22.04
            arch: arm64
            target: aarch64-linux-gnu
            name_suffix: linux_arm64
            extension: .so
          - os: windows-2022
            arch: x64
            name_suffix: windows_x64
            extension: .dll
          - os: windows-2022
            arch: x86
            name_suffix: windows_x86
            extension: .dll
          - os: macos-latest
            arch: x86_64
            name_suffix: macos_x64
            extension: .dylib
          - os: macos-14
            arch: arm64
            name_suffix: macos_arm
            extension: .dylib
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
        with:
          ref: "main"
      - run: git submodule update --init --recursive
      - name: Setup CMake
        if: startsWith(matrix.os, 'windows')
        uses: jwlawson/actions-setup-cmake@v1.13
      # - name: Setup Go (Windows only)
      #   if: startsWith(matrix.os, 'windows')
      #   uses: actions/setup-go@v4
      #   with:
      #     go-version: "^1.19.0"
      # - name: Setup MinGW (Windows only)
      #   if: startsWith(matrix.os, 'windows')
      #   uses: egor-tensin/setup-mingw@v2
      #   with:
      #     platform: ${{ matrix.arch }}
      #     version: 12.2.0
      - name: Build Library
        run: |
          cmake -B build -DCMAKE_BUILD_TYPE=Release -DUSEARCH_BUILD_LIB_C=0 -DUSEARCH_BUILD_SQLITE=1 -DUSEARCH_BUILD_TEST_CPP=0 -DUSEARCH_BUILD_BENCH_CPP=0
          cmake --build build --config Release
      - name: Prepare Library Artifact
        run: |
          cp build/libusearch_sqlite${{ matrix.extension }} usearch_sqlite_${{ matrix.name_suffix }}${{ matrix.extension }}
      - name: Upload Library Artifact
        uses: actions/upload-artifact@v2
        with:
          name: usearch_sqlite_${{ matrix.name_suffix }}
          path: usearch_sqlite_${{ matrix.name_suffix }}${{ matrix.extension }}

  prepare_release:
    name: Prepare Release
    needs: build_libraries
    runs-on: ubuntu-latest
    steps:
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: release-${{ github.run_number }}
          release_name: Release ${{ github.run_number }}
          draft: false
          prerelease: false
      - name: Download all build artifacts
        uses: actions/download-artifact@v2
        with:
          path: downloaded-artifacts
      - name: Upload artifacts to Release
        run: |
          find downloaded-artifacts -type f -exec bash -c 'curl \
            -X POST \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            -H "Content-Type: application/octet-stream" \
            --data-binary @{} \
            "${{ steps.create_release.outputs.upload_url }}?name=$(basename {})"' \;
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
