name: Build and Release Libraries

on:
  workflow_dispatch:

env:
  BUILD_TYPE: Release
  GH_TOKEN: ${{ secrets.SEMANTIC_RELEASE_TOKEN }}
  PYTHONUTF8: 1

permissions:
  contents: write
  id-token: write

jobs:
  versioning:
    name: Semantic Release
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - run: npm install --save-dev --prefix ./package-ci @semantic-release/exec @semantic-release/git conventional-changelog-eslint semantic-release && npx --prefix ./package-ci semantic-release
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          BUILD_TYPE: ${{ env.BUILD_TYPE }}
          PYTHONUTF8: ${{ env.PYTHONUTF8 }}

  create_linux_so_library:
    name: Create Linux SO Library
    runs-on: ubuntu-22.04
    needs: versioning
    strategy:
      matrix:
        include:
          - arch: amd64
            target: x86_64-linux-gnu
          - arch: arm64
            target: aarch64-linux-gnu
    steps:
      - uses: actions/checkout@v4
        with:
          ref: "main"
      - run: git submodule update --init --recursive
      - name: Build C/C++ SQLite Library
        run: |
          cmake -B build_release \
            -DCMAKE_BUILD_TYPE=Release \
            -DCMAKE_SYSTEM_NAME=Linux \
            -DCMAKE_SYSTEM_PROCESSOR=${{ matrix.arch }} \
            -DUSEARCH_BUILD_SQLITE=1
          cmake --build build_release --config Release
          cp build_release/libusearch_sqlite.so "usearch_sqlite_linux_${{ matrix.arch }}_${{ github.run_id }}.so"
      - name: Upload SO Library
        uses: actions/upload-artifact@v2
        with:
          name: usearch_sqlite_linux_${{ matrix.arch }}_lib
          path: usearch_sqlite_linux_${{ matrix.arch }}_${{ github.run_id }}.so

  create_windows_dll_library:
    name: Create Dll Library for Windows ${{ matrix.arch }}
    runs-on: windows-2022
    needs: versioning
    strategy:
      fail-fast: false
      matrix:
        arch: [x64, x86]
    steps:
      - uses: actions/checkout@v4
        with:
          ref: "main"
      - run: git submodule update --init --recursive

      - name: Setup CMake
        uses: jwlawson/actions-setup-cmake@v1.13

      - uses: actions/setup-go@v4
        with:
          go-version: "^1.19.0"

      - name: Setup MinGW
        uses: egor-tensin/setup-mingw@v2
        with:
          platform: ${{ matrix.arch }}
          version: 12.2.0

      - name: Build library
        run: |
          cmake -DCMAKE_BUILD_TYPE=Release -DUSEARCH_BUILD_LIB_C=0 -DUSEARCH_BUILD_SQLITE=1 -DUSEARCH_BUILD_TEST_CPP=0 -DUSEARCH_BUILD_BENCH_CPP=0 -B ./build_release
          cmake --build ./build_release --config Release

      - name: Copy the DLL file to the Artifact Directory
        run: |
          Copy-Item "build_release\usearch_sqlite.dll" -Destination "usearch_sqlite_windows_${{ matrix.arch }}_${{ github.run_id }}.dll"
      
      - name: Upload DLL Library
        uses: actions/upload-artifact@v2
        with:
          name: usearch_sqlite_windows_${{ matrix.arch }}_lib
          path: usearch_sqlite_windows_${{ matrix.arch }}_${{ github.run_id }}.dll

  create_macos_dylib_library:
    name: Create macOS DYLIB Library
    runs-on: macos-12
    needs: versioning
    strategy:
      matrix:
        arch: [arm64, x86_64]
    steps:
      - uses: actions/checkout@v4
        with:
          ref: "main"
      - run: git submodule update --init --recursive
      - name: Build library
        run: |
          cmake -DCMAKE_BUILD_TYPE=Release \
                -DUSEARCH_BUILD_SQLITE=1 \
                -DCMAKE_OSX_ARCHITECTURES=${{ matrix.arch }} \
                -B ./build_release
          cmake --build ./build_release --config Release
          cp ./build_release/libusearch_sqlite.dylib "usearch_sqlite_macos_${{ matrix.arch }}_${{ github.run_id }}.dylib"
      - name: Upload DYLIB Library
        uses: actions/upload-artifact@v2
        with:
          name: usearch_sqlite_macos_${{ matrix.arch }}_lib
          path: usearch_sqlite_macos_${{ matrix.arch }}_${{ github.run_id }}.dylib
